name: PR Checks

on:
  pull_request:

jobs:
  # this job builds and uploads the apk
  build_the_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: perform the checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # Verify the SHA-sum
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # This initializes gradle and sets up caching. Default version is the wrapper version.
    - name: gradle setup
      uses: gradle/actions/setup-gradle@v3
    - name: gradle build
      run: ./gradlew assemble bundle packageDebugAndroidTest :app:lint test

    # Lint
  ktlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: perform the checkout
      uses: actions/checkout@v3

    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: ktlint check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ktlintCheck
