name: PR Checks

on:
  pull_request:
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle-wrapper.properties'
      - 'gradle-wrapper.jar'
      - '.github/workflows/android_pr_build.yml'

jobs:
  # this job builds and uploads the apk
  build_the_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: perform the checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
        fetch-tags: true

    # Verify the SHA-sum
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # This initializes gradle and sets up caching. Default version is the wrapper version.
    - name: gradle setup
      uses: gradle/actions/setup-gradle@v4
    - name: gradle build
      run: ./gradlew assemble bundle packageFdroidDebugAndroidTest :app:lint test

    # Lint
  ktlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: perform the checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
        fetch-tags: true

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: gradle setup
      uses: gradle/actions/setup-gradle@v4
    - name: ktlint check
      run: ./gradlew ktlintCheck
