name: Signed APKs

on:
  push:
    branches:
      - table-layout

jobs:
  signed_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # Verify the SHA-sum
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: prepare for build
        shell: bash
        run: ./prepare_for_build.sh
        env:
          SERVICEACCOUNTJSON: ${{ secrets.SERVICEACCOUNTJSON }}
          KEYSTOREPASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
          KEYALIAS: ${{ secrets.KEYALIAS }}

      - name: gradle setup
        uses: gradle/actions/setup-gradle@v4
      - name: gradle build
        run: ./gradlew assemble

      - name: upload the generated files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          retention-days: 7
          name: artifacts
          path: app/build/outputs/apk
